# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optimal_by_optimizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import decision_pb2 as decision__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aoptimal_by_optimizer.proto\x12\x06skypie\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0e\x64\x65\x63ision.proto\"\xa8\x02\n\x12OptimalByOptimizer\x12\x34\n\x0eoptimizer_type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x12optimal_partitions\x18\x02 \x03(\x0b\x32\x10.skypie.Decision\x12.\n\tno_facets\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x38\n\x13partitioner_time_ns\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x44\n\x1fpartitioner_computation_time_ns\x18\x05 \x01(\x0b\x32\x1b.google.protobuf.Int64Valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimal_by_optimizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPTIMALBYOPTIMIZER']._serialized_start=87
  _globals['_OPTIMALBYOPTIMIZER']._serialized_end=383
# @@protoc_insertion_point(module_scope)
