# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import decision_pb2 as decision__pb2
import optimal_by_optimizer_pb2 as optimal__by__optimizer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trun.proto\x12\x06skypie\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0e\x64\x65\x63ision.proto\x1a\x1aoptimal_by_optimizer.proto\"\xcf\x05\n\x03Run\x12\x37\n\x12\x65numerator_time_ns\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12<\n\x16max_replication_factor\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12<\n\x16min_replication_factor\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x33\n\x0eno_app_regions\x18\x06 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x32\n\rno_dimensions\x18\x08 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12.\n\tno_facets\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x35\n\x10no_object_stores\x18\n \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x38\n\x13partitioner_time_ns\x18\x0f \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12 \n\x18object_stores_considered\x18\x10 \x03(\t\x12.\n\x14\x63\x61ndidate_partitions\x18\x11 \x03(\x0b\x32\x10.skypie.Decision\x12V\n\x1foptimal_partitions_by_optimizer\x18\x12 \x03(\x0b\x32-.skypie.Run.OptimalPartitionsByOptimizerEntry\x1a_\n!OptimalPartitionsByOptimizerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.skypie.OptimalByOptimizer:\x02\x38\x01\"a\n\x0eOutputDecision\x12\x38\n\x12replication_factor\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x15\n\robject_stores\x18\x02 \x03(\t\"k\n\x18OutputOptimalByOptimizer\x12\x38\n\x12replication_factor\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12\x15\n\robject_stores\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'run_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _RUN_OPTIMALPARTITIONSBYOPTIMIZERENTRY._options = None
  _RUN_OPTIMALPARTITIONSBYOPTIMIZERENTRY._serialized_options = b'8\001'
  _globals['_RUN']._serialized_start=98
  _globals['_RUN']._serialized_end=817
  _globals['_RUN_OPTIMALPARTITIONSBYOPTIMIZERENTRY']._serialized_start=722
  _globals['_RUN_OPTIMALPARTITIONSBYOPTIMIZERENTRY']._serialized_end=817
  _globals['_OUTPUTDECISION']._serialized_start=819
  _globals['_OUTPUTDECISION']._serialized_end=916
  _globals['_OUTPUTOPTIMALBYOPTIMIZER']._serialized_start=918
  _globals['_OUTPUTOPTIMALBYOPTIMIZER']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
