# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tier_advise.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import run_pb2 as run__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tier_advise.proto\x12\x06skypie\x1a\trun.proto\"\x9e\x01\n\nTierAdvise\x12\x45\n\x12replication_factor\x18\x01 \x03(\x0b\x32).skypie.TierAdvise.ReplicationFactorEntry\x1aI\n\x16ReplicationFactorEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.skypie.Setting:\x02\x38\x01\"l\n\x07Setting\x12\'\n\x04runs\x18\x01 \x03(\x0b\x32\x19.skypie.Setting.RunsEntry\x1a\x38\n\tRunsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.skypie.Run:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tier_advise_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _TIERADVISE_REPLICATIONFACTORENTRY._options = None
  _TIERADVISE_REPLICATIONFACTORENTRY._serialized_options = b'8\001'
  _SETTING_RUNSENTRY._options = None
  _SETTING_RUNSENTRY._serialized_options = b'8\001'
  _globals['_TIERADVISE']._serialized_start=41
  _globals['_TIERADVISE']._serialized_end=199
  _globals['_TIERADVISE_REPLICATIONFACTORENTRY']._serialized_start=126
  _globals['_TIERADVISE_REPLICATIONFACTORENTRY']._serialized_end=199
  _globals['_SETTING']._serialized_start=201
  _globals['_SETTING']._serialized_end=309
  _globals['_SETTING_RUNSENTRY']._serialized_start=253
  _globals['_SETTING_RUNSENTRY']._serialized_end=309
# @@protoc_insertion_point(module_scope)
